# Generated by Django 5.2.8 on 2025-11-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active_ingredient', models.CharField(max_length=150)),
                ('dosage_form', models.CharField(max_length=150)),
                ('indications', models.TextField()),
                ('side_effects', models.TextField(blank=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='pharma_shelf_app.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs_created', to='pharma_shelf_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='DrugAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_for', to='pharma_shelf_app.drug')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='pharma_shelf_app.drug')),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='pharma_shelf_app.drug')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='pharma_shelf_app.drug')),
            ],
        ),
    ]
