# Generated by Django 5.2.8 on 2025-11-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_shelf_app', '0002_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='pharmacist', max_length=50),
        ),
    ]
